/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tinytimrob_jfreetype2_JNIFreeType */

#ifndef _Included_com_tinytimrob_jfreetype2_JNIFreeType
#define _Included_com_tinytimrob_jfreetype2_JNIFreeType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tinytimrob_jfreetype2_JNIFreeType
 * Method:    FT_Init_FreeType
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_com_tinytimrob_jfreetype2_JNIFreeType_FT_1Init_1FreeType
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_tinytimrob_jfreetype2_JNIFreeType
 * Method:    FT_Done_FreeType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tinytimrob_jfreetype2_JNIFreeType_FT_1Done_1FreeType
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
